/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import NapakalakiGame.Player;

/**
 *
 * @author saytes
 */
public class PlayerView extends javax.swing.JPanel {

    /**
     * Creates new form PlayerView
     */
    private Player playerModel;
    public PlayerView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JLabel();
        level = new javax.swing.JLabel();
        dead = new javax.swing.JLabel();
        canISteal = new javax.swing.JLabel();
        hidden = new javax.swing.JLabel();
        enemy = new javax.swing.JLabel();
        pendingBad = new javax.swing.JLabel();
        sectario = new javax.swing.JLabel();
        visible = new javax.swing.JLabel();
        visibles = new javax.swing.JPanel();
        ocultos = new javax.swing.JPanel();

        name.setText("jLabel1");

        level.setText("jLabel1");

        dead.setText("jLabel1");

        canISteal.setText("jLabel1");

        hidden.setText("Tesoros Ocultos");

        enemy.setText("jLabel1");

        pendingBad.setText("jLabel1");

        sectario.setText("jLabel1");

        visible.setText("Tesoros Visibles");

        visibles.setBorder(new javax.swing.border.MatteBorder(null));

        ocultos.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(visible, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(dead))
                    .addComponent(visibles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(level))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hidden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ocultos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name)
                            .addComponent(sectario)
                            .addComponent(pendingBad)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(canISteal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(enemy)))
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name)
                    .addComponent(level)
                    .addComponent(dead))
                .addGap(18, 18, 18)
                .addComponent(sectario)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hidden)
                    .addComponent(visible))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ocultos, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(visibles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(pendingBad, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(canISteal)
                    .addComponent(enemy))
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setPlayer(Player p){
        playerModel = p;
        this.name.setText(p.getName());
        String puedes = "Puedes robar.";
        String muerto = "Estás muerto.";
        
        if (p.isDeath() == false){
           muerto = "Estás vivo";
        }
        if (p.canISteal() == false){
            puedes = "Ya has robado.";
        }
        this.canISteal.setText(puedes);
        this.dead.setText(muerto);
        this.enemy.setText(p.getEnemy().toString());
        this.level.setText(Integer.toString(p.getLevel()));
        this.pendingBad.setText(p.getPendingBadConsequence().toString());
           
        repaint();
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel canISteal;
    private javax.swing.JLabel dead;
    private javax.swing.JLabel enemy;
    private javax.swing.JLabel hidden;
    private javax.swing.JLabel level;
    private javax.swing.JLabel name;
    private javax.swing.JPanel ocultos;
    private javax.swing.JLabel pendingBad;
    private javax.swing.JLabel sectario;
    private javax.swing.JLabel visible;
    private javax.swing.JPanel visibles;
    // End of variables declaration//GEN-END:variables
}
